# Generated by Django 2.2 on 2019-04-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0002_auto_20190424_1601'),
        ('chats', '0002_auto_20190424_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user_profile.Profile')),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.Channel')),
            ],
        ),
    ]
